```{r SETUP}
options(stringsAsFactors = FALSE)
library(Seurat)
library(harmony)
library(tidyverse)
library(edgeR)
```

Generated RNA count matrices of cells (rows) by genes (columns)

QCs the data and generates the Seurat object

```{r QC}

samples <- data.frame(
  path = c(
    "~/Documents/LOOTS_DATA/adultctrlstromal_filtered_feature_bc_matrix",
    "~/Documents/LOOTS_DATA/adultsostabstromal_filtered_feature_bc_matrix",
    "~/Documents/LOOTS_DATA/oldctrlcd45minus_filtered_feature_bc_matrix",
    "~/Documents/LOOTS_DATA/oldsostabcd45minus_filtered_feature_bc_matrix"
  ),
  names = c(
    "PBS_young",
    "Sost_young",
    "PBS_old",
    "Sost_old"
  ),
  min_feature = c(300, 300, 300, 300),
  max_feature = c(8000, 8000, 7500, 7500),
  max_mt_count   = c(6, 6, 6, 6)
)

obj_list <- lapply(1:nrow(samples), function(i){
  data <- Read10X(data.dir = samples$path[i])
  obj <- CreateSeuratObject(counts = data, min.cells = 3, min.features = 200)
  obj[["percent.mt"]] <- PercentageFeatureSet(obj, pattern = "^mt-")
  obj$which_sample <- samples$names[i]
  obj <- subset(obj,
                subset = nFeature_RNA > samples$min_feature[i] &
                  nFeature_RNA < samples$max_feature[i] &
                  percent.mt   < samples$max_mt_count[i]
  )
  obj <- obj[!grepl("^mt-", rownames(obj)), ]
  obj <- NormalizeData(obj)
  obj <- JoinLayers(obj)
  obj <- FindVariableFeatures(obj, selection.method = "vst", nfeatures = 2000)
  obj <- ScaleData(obj)
  obj <- RunPCA(obj)
  return(obj)
})

merged_obj <- merge(
  x = obj_list[[1]], 
  y = obj_list[2:4], 
  add.cell.ids = samples$names
)

merged_obj <- NormalizeData(merged_obj)
merged_obj <- JoinLayers(merged_obj)
merged_obj <- FindVariableFeatures(merged_obj, selection.method = "vst", nfeatures = 2000)
merged_obj <- ScaleData(merged_obj)
merged_obj <- RunPCA(merged_obj)

table(merged_obj$which_sample)

violin_plot <- VlnPlot(merged_obj,
                       features = c("nFeature_RNA", "nCount_RNA", "percent.mt"),
                       ncol = 3,
                       pt.size = 0.1,
                       group.by = "which_sample")
ggsave("~/Desktop/SOST_violin_after.png", plot = violin_plot, width = 16, height = 6, dpi = 300)

plot1 <- FeatureScatter(merged_obj, feature1 = "nCount_RNA", feature2 = "percent.mt", group.by = "which_sample")
plot2 <- FeatureScatter(merged_obj, feature1 = "nCount_RNA", feature2 = "nFeature_RNA", group.by = "which_sample")
combined_scatter <- plot1 + plot2
ggsave("~/Desktop/SOST_feature_scatter_after.png", plot = combined_scatter, width = 15, height = 7, dpi = 300)

```

Integrate all samples together

```{r INTEGRATE}

rm(list = setdiff(ls(), "merged_obj"))
gc()

obj_list <- SplitObject(merged_obj, split.by = "which_sample")
integ_obj <- lapply(X = obj_list, FUN = function(x) {
  x <- NormalizeData(x)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000)
})
rm(obj_list, merged_obj)
gc()

features <- SelectIntegrationFeatures(object.list = integ_obj)
integ_obj <- lapply(X = integ_obj, FUN = function(x) {
  x <- ScaleData(x, features = features)
  x <- RunPCA(x, features = features)
})

integ_anchors <- FindIntegrationAnchors(object.list = integ_obj, anchor.features = features, reduction = "rpca")
rm(integ_obj)
gc()

integ_final <- IntegrateData(anchorset = integ_anchors)
DefaultAssay(integ_final) <- "integrated"
rm(integ_anchors)
gc()

integ_final <- ScaleData(integ_final)
integ_final <- RunPCA(integ_final)
ElbowPlot(integ_final, ndims = 50, reduction = "pca") 
integ_final <- FindNeighbors(integ_final, reduction = "pca", dims = 1:30)
integ_final <- FindClusters(integ_final, resolution = 0.4)
immune_removed <- RunUMAP(immune_removed, reduction = "pca", dims = 1:30)

UMAP_master <- DimPlot(integ_final, reduction = "umap", label = TRUE, repel = TRUE, label.size = 9, label.box = TRUE) + 
  xlab("UMAP 1") + 
  ylab("UMAP 2") + 
  NoLegend() +
  theme(
    axis.title = element_text(size = 20),
    axis.text = element_text(size = 15)
  )
ggsave("~/Desktop/SOST_UMAP_master_integrated.png", plot = UMAP_master, width = 12, height = 8, dpi = 300)
UMAP_split <- DimPlot(integ_final, split.by = "which_sample", ncol = 2, reduction = "umap", label = FALSE) + 
  xlab("UMAP 1") + 
  ylab("UMAP 2") + 
  theme(
    axis.title = element_text(size = 20),
    axis.text = element_text(size = 15),
    strip.text = element_text(size = 18),
    legend.text = element_text(size = 15),
    legend.title = element_text(size = 18)
  )
ggsave("~/Desktop/SOST_UMAP_split_integrated.png", plot = UMAP_split, width = 14, height = 8, dpi = 300)

rm(list = setdiff(ls(), "integ_final"))
gc()

save(integ_final, file = "~/Documents/LOOTS_DATA/SOST_bone_mass_integ_object.RData")
load("~/Documents/LOOTS_DATA/SOST_bone_mass_integ_object.RData")

```

Filter out immune cells and remove clusters

```{r IMMUNE}

features <- c("Pecam1", "Ptprc", "Rgs5", "Hemgn")
p1 <- FeaturePlot(integ_final, features = features, order = TRUE, ncol = 2) & 
  xlab("UMAP 1") & 
  ylab("UMAP 2") & 
  theme(
    plot.title = element_text(size = 20),
    axis.title = element_text(size = 18),  
    axis.text = element_text(size = 14),
    legend.text = element_text(size = 12),
    legend.key.size = unit(0.8, "cm")
  )
ggsave("~/Desktop/SOST_feature_plot_immune_markers.png", plot = p1, width = 12, height = 10, dpi = 300)

keep_clusters <- c("0","1","12","9","4","6","3","2")
immune_removed <- subset(integ_final, idents = keep_clusters)

ElbowPlot(immune_removed, ndims = 50, reduction = "pca") 
immune_removed <- FindNeighbors(immune_removed, reduction = "pca", dims = 1:10)
immune_removed <- FindClusters(immune_removed, resolution = 0.4)
immune_removed <- RunUMAP(immune_removed, reduction = "pca", dims = 1:10)

UMAP_master <- DimPlot(immune_removed, reduction = "umap", label = TRUE, repel = TRUE, label.size = 9, label.box = TRUE, pt.size = 1.0) + 
  xlab("UMAP 1") + 
  ylab("UMAP 2") + 
  NoLegend() +
  theme(
    axis.title = element_text(size = 20),
    axis.text = element_text(size = 15)
  )
ggsave("~/Desktop/SOST_UMAP_master_immune_removed.png", plot = UMAP_master, width = 12, height = 8, dpi = 300)
UMAP_split <- DimPlot(immune_removed, split.by = "which_sample", ncol = 2, reduction = "umap", label = FALSE, pt.size = 1.0) + 
  xlab("UMAP 1") + 
  ylab("UMAP 2") + 
  theme(
    axis.title = element_text(size = 20),
    axis.text = element_text(size = 15),
    strip.text = element_text(size = 18),
    legend.text = element_text(size = 15),
    legend.title = element_text(size = 18)
  )
ggsave("~/Desktop/SOST_UMAP_split_immune_removed.png", plot = UMAP_split, width = 12, height = 8, dpi = 300)


rm(list = setdiff(ls(), "immune_removed"))
gc()
```

Identify and plot all marker genes for each cluster

```{r MARKERS}

DefaultAssay(immune_removed) <- "RNA"

bone_markers <- c(
  "Runx2", "Lifr", "Postn", "Mmp13", "Alpl",
  "Col1a2", "Col1a1", "Bglap", "Bglap2", "Mepe",
  "Sost", "Dmp1", "Dkk1", "Epcam", "Tnfrsf11b",
  "Omd", "Cytl1", "Prg4", "Frzb", "Lepr", "Kitl",
  "Adipoq", "Cxcl12", "Lpl", "Ucma", "Matn3", "Acan",
  "Col2a1", "Hapln1", "Gsn", "Dcn", "Col14a1", "S100a4",
  "Col3a1", "Pdpn", "Pdgfa", "Cd109", "Phex", "Bambi"
)

feature_markers <- c("Postn", "Bglap", "Sost", "Cxcl12", "S100a4", "Col2a1")

p1 <- FeaturePlot(immune_removed, features = feature_markers, order = TRUE, ncol = 2) & 
  xlab("UMAP 1") & 
  ylab("UMAP 2") & 
  theme(
    plot.title = element_text(size = 20),
    axis.title = element_text(size = 18),  
    axis.text = element_text(size = 14),
    legend.text = element_text(size = 12),
    legend.key.size = unit(0.8, "cm")
  )
ggsave("~/Desktop/SOST_feature_plot_bone_markers.png", plot = p1, width = 12, height = 10, dpi = 300)


p2 <- DotPlot(immune_removed, features = bone_markers) + 
  RotatedAxis()
ggsave("~/Desktop/SOST_dotplot_bone_markers.png", plot = p2, width = 15, height = 8, dpi = 300)

# integ_subset <- subset(immune_removed, idents = c("7", "6"))
# integ_subset <- JoinLayers(integ_subset)
# integ_subset <- NormalizeData(integ_subset)
# markers <- FindAllMarkers(integ_subset, 
#                            only.pos = TRUE, 
#                            min.pct = 0.25,
#                            logfc.threshold = 0.25)
# top_markers <- markers[markers$p_val_adj < 0.05, ]
# # top_markers$unique <- !duplicated(top_markers$gene) & 
# #                       !duplicated(top_markers$gene, fromLast = TRUE)
# write.csv(top_markers, "~/Desktop/SOST_7_marker_genes.csv")

rm(list = setdiff(ls(), "immune_removed"))
gc()

```

Identify population shifts

```{r SHIFTS}

integ_final_annotated <- RenameIdents(immune_removed,
                                       '0' = "aCAR",
                                       '1' = "OCY",
                                       '2' = "MP_FB",      
                                        '3' = "OB",
                                       '4' = "OCP",
                                        '5' = "pOB",
                                        '6' = "MP_FB",
                                        '7' = "OB", 
                                       '8' = "CH",
                                      '9' = "pOB"
)

UMAP_master <- DimPlot(integ_final_annotated, reduction = "umap", label = TRUE, repel = TRUE, label.size = 9, label.box = TRUE, pt.size = 1.0) + 
  xlab("UMAP 1") + 
  ylab("UMAP 2") + 
  NoLegend() +
  theme(
    axis.title = element_text(size = 20),
    axis.text = element_text(size = 15)
  )
ggsave("~/Desktop/SOST_UMAP_master_annotated.png", plot = UMAP_master, width = 12, height = 8, dpi = 300)
UMAP_split <- DimPlot(integ_final_annotated, split.by = "which_sample", ncol = 2, reduction = "umap", label = FALSE, pt.size = 1.0) + 
  xlab("UMAP 1") + 
  ylab("UMAP 2") + 
  theme(
    axis.title = element_text(size = 20),
    axis.text = element_text(size = 15),
    strip.text = element_text(size = 18),
    legend.text = element_text(size = 15),
    legend.title = element_text(size = 18)
  )
ggsave("~/Desktop/SOST_UMAP_split_integrated_annotated.png", plot = UMAP_split, width = 12, height = 8, dpi = 300)


cell_stats <- as.data.frame(prop.table(table(Idents(integ_final_annotated), 
                                             integ_final_annotated$which_sample), margin = 2) * 100)
colnames(cell_stats) <- c("Type", "Sample", "Percent")

comparisons <- list(
  "Young_Sost_vs_PBS" = c("PBS_young", "Sost_young"),
  "Old_Sost_vs_PBS"   = c("PBS_old", "Sost_old"),
  "Sost_Old_vs_Young" = c("Sost_young", "Sost_old")
)

cell_types_ordered <- levels(Idents(integ_final_annotated))

for (n in names(comparisons)) {
  ref_name <- comparisons[[n]][1]
  test_name <- comparisons[[n]][2]
  
  sub <- cell_stats[cell_stats$Sample %in% comparisons[[n]], ]
  sub$Sample <- factor(sub$Sample, levels = c(ref_name, test_name))
  
  p <- ggplot(sub, aes(x = Sample, y = Percent, fill = Type)) +
    geom_bar(stat = "identity", width = 0.7) +
    theme_classic() +
    theme(
      text = element_text(size = 22),
      axis.text = element_text(size = 20, color = "black"),
      axis.title = element_text(size = 24),
      legend.text = element_text(size = 18)
    ) +
    geom_text(aes(label = ifelse(Percent > 2, paste0(round(Percent, 1), "%"), "")), 
              position = position_stack(vjust = 0.5), size = 6, fontface = "bold")
  
  ggsave(paste0("~/Desktop/SOST_pop_", n, ".png"), plot = p, width = 10, height = 10, dpi = 300)
  
  ref_df <- sub[sub$Sample == ref_name, ]
  test_df <- sub[sub$Sample == test_name, ]
  
  tab <- merge(ref_df, test_df, by = "Type", suffixes = c("_Ref", "_Test"))
  tab <- tab[match(cell_types_ordered, tab$Type), ]
  
  tab$Relative_Change_Percent <- round(((tab$Percent_Test - tab$Percent_Ref) / (tab$Percent_Ref + 1e-6)) * 100, 2)
  
  tab$Direction <- ifelse(tab$Relative_Change_Percent > 0, "Increased", 
                          ifelse(tab$Relative_Change_Percent < 0, "Decreased", "No Change"))
  
  write.csv(tab[, c("Type", "Percent_Ref", "Percent_Test", "Relative_Change_Percent", "Direction")], 
            paste0("~/Desktop/SOST_stats_", n, ".csv"), row.names = FALSE)
}


rm(list = setdiff(ls(), "integ_final_annotated"))
gc()

save(integ_final_annotated, file = "~/Documents/LOOTS_DATA/SOST_bone_mass_integ_annotated_object.RData")
#load("~/Documents/LOOTS_DATA/SOST_bone_mass_integ_object.RData")

```